apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  namespace: default
  labels:
    app: employee
spec:
  selector:
    matchLabels:
      app: employee
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: oengajohn/employee-service:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 20
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: cluster-config-map
              key: mysql-database-host
        - name: EMPLOYEE_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: cluster-config-map
              key: employee-database-name
        - name: DEPARTMENT_SERVICE_HOST_URL
          valueFrom:
            configMapKeyRef:
              name: cluster-config-map
              key: department-service-host
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: cluster-config-map
              key: mysql-database-port
        - name: MYSQL_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: cluster-secret
              key: mysql-root-username
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-secret
              key: mysql-root-password
        ports:
        - containerPort: 8080
          name: employee
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: employee-lb
  namespace: default
spec:
  selector:
    app: employee
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: employee
    protocol: TCP
    port: 80
    targetPort: 8080

